name: 'cloudbase-framework-actions'
author: 'i@beetcb.com'
description: 'zero configuration deployment for cloudbase'

inputs:
  secretId:
    description: 'secretId to access Tencent API'
    required: true
  secretKey:
    description: 'secretKey to access Tencent API'
    required: true
  envId:
    description: 'envId to find cloudbase environment'
    required: true

runs:
  using: 'composite'
  steps:
    - run: sudo bash ${{ github.action_path }}/set.sh ${{ inputs.secretId }} ${{ inputs.secretKey }} ${{ inputs.envId }}
      shell: bash
